# from http://www.iso.org/iso/list-en1-semic-3.txt
_COUNTRY_CODE_TO_COUNTRY = {
        'AL': 'ALBANIA',
        'AD': 'ANDORRA',
        'AT': 'AUSTRIA',
        'BY': 'BELARUS',
        'BE': 'BELGIUM',
        'BA': 'BOSNIA AND HERZEGOVINA',
        'BG': 'BULGARIA',
        'HR': 'CROATIA',
        'CY': 'CYPRUS',
        'CZ': 'CZECH REPUBLIC',
        'DK': 'DENMARK',
        'EE': 'ESTONIA',
        'FO': 'FAROE ISLANDS',
        'FI': 'FINLAND',
        'FR': 'FRANCE',
        'DE': 'GERMANY',
        'GI': 'GIBRALTAR',
        'GR': 'GREECE',
        'GL': 'GREENLAND',
        'HU': 'HUNGARY',
        'IS': 'ICELAND',
        'IE': 'IRELAND',
        'IT': 'ITALY',
        'LV': 'LATVIA',
        'LI': 'LIECHTENSTEIN',
        'LT': 'LITHUANIA',
        'LU': 'LUXEMBOURG',
        'MK': 'MACEDONIA',
        'MT': 'MALTA',
        'MD': 'MOLDOVA',
        'MC': 'MONACO',
        'ME': 'MONTENEGRO',
        'NL': 'NETHERLANDS',
        'NO': 'NORWAY',
        'PL': 'POLAND',
        'PT': 'PORTUGAL',
        'RO': 'ROMANIA',
        'RU': 'RUSSIAN FEDERATION',
        'SM': 'SAN MARINO',
        'RS': 'SERBIA',
        'SK': 'SLOVAKIA',
        'SI': 'SLOVENIA',
        'ES': 'SPAIN',
        'SE': 'SWEDEN',
        'CH': 'SWITZERLAND',
        'TR': 'TURKEY',
        'UA': 'UKRAINE',
        'GB': 'UNITED KINGDOM',
        'VA': 'VATICAN CITY',
    }